name: 🕵️ Deploy to quality assurance

on: workflow_dispatch

jobs:
    deploy:
        name: 🚀 Deploy
        environment:
            name: qa-cp-map
            url: https://qa-capitalprojects.nycplanningdigital.com
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 'Install Heroku CLI'
              run: curl https://cli-assets.heroku.com/install.sh | sh
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.13.15
              with:
                heroku_email: ${{secrets.HEROKU_EMAIL}}
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                team: ${{secrets.HEROKU_TEAM}}
              env:
                HD_VITE_ZONING_API_URL: ${{secrets.VITE_ZONING_API_URL}}
                HD_VITE_CPDB_DATA_URL: ${{secrets.VITE_CPDB_DATA_URL}}
                HD_VITE_FEATURE_FLAG_ATTRIBUTE_FILTERS: ${{secrets.VITE_FEATURE_FLAG_ATTRIBUTE_FILTERS}}
                HD_VITE_BASEMAP_URL: ${{vars.VITE_BASEMAP_URL}}
